(TeX-add-style-hook "p"
 (lambda ()
    (TeX-run-style-hooks
     "lipsum"
     "etoolbox"
     "subfigure"
     "floatrow"
     "graphicx"
     "geometry"
     "listings"
     "multicol"
     "multirow"
     "CJKutf8"
     ""
     "fontenc"
     "T1"
     "inputenc"
     "utf8"
     "latex2e"
     "scrartcl11"
     "scrartcl"
     "titlepage"
     "abstraction"
     "11pt"
     "b5paper")))

